function cfg = lt_default_channel(sample_rate, snr_db, seed)
%LT_DEFAULT_CHANNEL  Convenience struct of channel impairments (channel.m values).

if nargin < 2, snr_db = Inf; end
if nargin < 3, seed = 1; end
cfg = struct( ...
    'sample_rate',      sample_rate, ...
    'freq_offset',      0, ...
    'phase_offset_deg', 0, ...
    'timing_ppm',       0, ...
    'dc_offset',        0, ...
    'snr_db',           snr_db, ...
    'seed',             seed);
end
